site_name: Featureform API Reference

# Repository
repo_name: featureform/featureform
repo_url: https://github.com/featureform/featureform
edit_uri: ""

theme:
    name: "material"
    favicon: "images/featureform.png"
    palette:
        scheme: default
        primary: custom
        accent: custom
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Register:
    - Providers: providers.md
    - Sources: sources.md
    - Features: features.md
    - Training Sets: training_sets.md
  - Apply:
      - Client: client.md
      - CLI: cli.md
  - Serve: serve.md
  - Get: get.md
  - Deployment Feature Compatibility: compatibility.md

plugins:
- search
- section-index
- mkdocstrings:
    handlers:
        python:
            paths: [src]
- gen-files:
    scripts:
    - gen_pages.py
#- literate-nav:
#      nav_file: index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences