site_name: Featureform API Reference
theme:
    name: "material"
    palette:
        scheme: "slate"
        primary: "pink"
        accent: "pink"
plugins:
- search
- mkdocstrings
- gen-files:
    scripts:
    - gen_pages.py
- literate-nav:
      nav_file: index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences