apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: featureform-prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: featureform-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: featureform-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: featureform-prometheus
subjects:
  - kind: ServiceAccount
    name: default
