apiVersion: v1
kind: Service
metadata:
  name: featureform-metadata-server
spec:
  ports:
    - name: grpc
      port: {{ .Values.metadata.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: featureform-metadata-server
