#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

apiVersion: v1
kind: Service
metadata:
  name: featureform-metadata-server
spec:
  ports:
    - name: grpc
      port: {{ .Values.metadata.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: featureform-metadata-server
