apiVersion: v1
kind: Service
metadata:
  name: featureform-coordinator
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "coordinator.selectorLabels" . | nindent 4 }}
