#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: featureform-prometheus-server-conf
  labels:
    name: featureform-prometheus-server-conf
data:
  prometheus.rules: |-
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:9090']
      - job_name: 'featureform-service-monitoring'
        scrape_interval: 10s
        metrics_path: /metrics
        static_configs:
          - targets: ["featureform-feature-server:2112"]
