#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: featureform-prometheus-deployment
  labels:
    app: featureform-prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featureform-prometheus-server
  template:
    metadata:
      labels:
        app: featureform-prometheus-server
      {{ if .Values.restartOnUpdate }}
      annotations:
        timestamp: {{ now | quote }}
      {{ end }}
    spec:
      containers:
        - name: featureform-prometheus
          image: {{ .Values.prometheus.image }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.route-prefix=/prometheus"
            - "--web.external-url=http://{{ .Release.Name }}-featureform.featureform.com/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: featureform-prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: featureform-prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: featureform-prometheus-config-volume
          configMap:
            defaultMode: 420
            name: featureform-prometheus-server-conf

        - name: featureform-prometheus-storage-volume
          emptyDir: {}
