apiVersion: v1
kind: Service
metadata:
  name: featureform-prometheus-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"

spec:
  selector:
    app: featureform-prometheus-server
  type: ClusterIP
  ports:
    - port: {{ .Values.prometheus.port }}
      targetPort: 9090
