apiVersion: v1
kind: Service
metadata:
  name: iceberg-streamer
spec:
  selector:
    app: iceberg-streamer
  ports:
  - name: grpc
    protocol: TCP
    port: 8085
    targetPort: 8085
  type: ClusterIP