apiVersion: v1
kind: Service
metadata:
  name: featureform-api-server
  labels:
    run: featureform-api-server
spec:
  # bypass kube-proxy
  ports:
    - port: 7878
      protocol: TCP
      targetPort: 7878
  type: ClusterIP
  selector:
    app: featureform-api-server