{{ if .Values.publicCert }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-featureform-prod
spec:
  secretName: featureform-ca-secret
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - {{ .Values.hostname }}
{{ end }}