#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

{{ if .Values.selfSignedCert }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: featureform-ca-cert
spec:
  secretName: featureform-ca
  dnsNames:
    - {{ .Values.hostname }}
  issuerRef:
    name: letsencrypt-prod
{{ end }}