apiVersion: v1
kind: Service
metadata:
  name: featureform-feature-server
spec:
  ports:
    - name: grpc
      port: {{ .Values.serving.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: featureform-feature-server
