#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

{{ if .Values.psql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: psql-secret-literal
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # Needed to ensure this is created before the DB migration pre-install job.
    "helm.sh/hook-weight": "-6"
type: kubernetes.io/basic-auth
stringData:
  user: {{ .Values.psql.user | quote }}
  password: {{ .Values.psql.password | quote }}
  connection-string: "postgres://{{ .Values.psql.user }}:{{ .Values.psql.password | urlquery }}@{{ .Values.psql.host }}:{{ .Values.psql.port }}/{{ .Values.psql.db }}"
{{ end }}
