apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: featureform-metadata-server
spec:
  ports:
    - name: grpc
      port: {{ .Values.grpc.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    run: featureform-metadata-server
status:
  loadBalancer: {}
