apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: featureform
    run: featureform-feature-server
    app: featureform-feature-server
  name: featureform-feature-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: featureform-feature-server
      app: featureform-feature-server
  strategy: {}
  template:
    metadata:
      labels:
        chart: featureform
        run: featureform-feature-server
        app: featureform-feature-server
      annotations:
        timestamp: {{ now | quote }}  
    spec:
      containers:
        - image: "{{ .Values.global.repo | default .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.global.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          name: featureform-feature-server
          ports:
            - containerPort: {{ .Values.serving.port }}
            - containerPort: {{ .Values.metrics.port }}
          env:
            - name: SERVING_PORT
              value: {{ .Values.serving.port | quote }}
            - name: METRICS_PORT
              value: 0.0.0.0:{{ .Values.metrics.port }}
            - name: METADATA_HOST
              value: {{ .Values.metadata.host }}
            - name: METADATA_PORT
              value: {{ .Values.metadata.port | quote }}
          resources: {}
status: {}
