apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-proxy
  template:
    metadata:
      labels:
        app: iceberg-proxy
    spec:
      containers:
      - name: iceberg-proxy
        image: local/iceberg-proxy:stable
        ports:
        - containerPort: 8086
        env:
        - name: ICEBERG_STREAMER_ADDRESS
          value: "iceberg-streamer:8085"