#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

{{ if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: featureform-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: "{{ .Values.repository | default .Values.image.repository }}/backup:{{ .Values.versionOverride | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.pullPolicy }}
              name: featureform-backup
              env:
                - name: ETCD_HOSTNAME
                  value: "featureform-etcd"
                - name: ETCD_PORT
                  value: "2379"
                - name: ETCD_USERNAME
                  value: "root"
                - name: ETCD_PASSWORD
                  value: "secretpassword"
              envFrom:
                - secretRef:
                    name: featureform-backup
          restartPolicy: Never
{{ end }}