#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-upgrade-configmap
data:
  ETCD_INITIAL_CLUSTER_STATE:
    { { ternary "new" "existing" .Release.IsInstall | quote } }
