apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: featureform
    run: featureform-metadata-server
    app: featureform-metadata-server
  name: featureform-metadata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      chart: featureform
      run: featureform-metadata-server
      app: featureform-metadata-server
  strategy: {}
  template:
    metadata:
      labels:
        chart: featureform
        run: featureform-metadata-server
        app: featureform-metadata-server
    spec:
      containers:
        - image: "{{ .Values.global.repo | default .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.global.version | default .Chart.AppVersion }}"
          name: featureform-metadata-server
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: MEILISEARCH_PORT
              value: {{ .Values.search.port | quote }}
            - name: MEILISEARCH_HOST
              value: {{ .Values.search.host }}
            - name: MEILISEARCH_APIKEY
              value: {{ .Values.search.apikey | quote }}
            - name: ETCD_HOST
              value: {{ .Values.etcd.host  }}
            - name: ETCD_PORT
              value: {{ .Values.etcd.port | quote }}
status: {}
