apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: featureform-api-server
    chart: featureform
  name: featureform-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featureform-api-server
  strategy: {}
  template:
    metadata:
      labels:
        app: featureform-api-server
      {{ if .Values.restartOnUpdate }}
      annotations:
        timestamp: {{ now | quote }}
      {{ end }}
    spec:
      containers:
        - image: "{{ .Values.repository }}/{{ .Values.api.image.name }}:{{ .Values.versionOverride | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: featureform-api-server
          ports:
            - containerPort: {{ .Values.api.port  }}
              protocol: TCP
          env:
            - name: API_PORT
              value: {{ .Values.api.port | quote }}
            - name: METADATA_HOST
              value: {{ .Values.metadata.host }}
            - name: METADATA_PORT
              value: {{ .Values.metadata.port | quote }}
            - name: SERVING_HOST
              value: {{ .Values.serving.host }}
            - name: SERVING_PORT
              value: {{ .Values.serving.port | quote }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /_ah/
              port: 8443
            initialDelaySeconds: 300
            periodSeconds: 3
