#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

apiVersion: v1
kind: Service
metadata:
  name: featureform-api-server
  labels:
    run: featureform-api-server
spec:
  ports:
    - name: grpc-port
      port: {{ .Values.api.port }}
      protocol: TCP
      targetPort: 7878
    - name: status-port
      port: {{ .Values.api.statusPort }}
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  selector:
    app: featureform-api-server
