apiVersion: v1
kind: Service
metadata:
  name: featureform-api-server
  labels:
    app: featureform-api-server
spec:
  ports:
    - port: {{ .Values.api.port }}
      protocol: TCP
      targetPort: 7878
  type: ClusterIP
  selector:
    app: featureform-api-server