apiVersion: v1
kind: Service
metadata:
  name: featureform-coordinator
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.coordinator.port }}
      targetPort: http
      protocol: TCP
      name: http
