name: Embedding Store CI
on: [push]
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1

        - name: Mount bazel cache
        uses: actions/cache@v1
        with:
            path: "/home/runner/.cache/bazel"
            key: bazel

        - name: Test
          run: bazel test //...

        - name: Build
          run: bazel build //...
