name: client-ci 
on:
  push:
    branches:
      - main
jobs:
  clientdocs:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - run: pip install mkdocs mkdocs-material mkdocstrings-python mkdocs-gen-files mkdocs-literate-nav mkdocs-section-index
      - run: mkdocs gh-deploy --force