name: Update Pypi
on: 
  workflow_dispatch: 
    inputs:
      version:
        description: 'Version of python package to deploy'
        required: true
        type: string
jobs:
  python:
    name: Package Python
    environment: Deployment
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install grpc_tools
        run: pip install grpcio-tools

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Install Build Deps
        run: |
          pip install build
          pip install twine

      - name: Set Version Number
        run: sed -i -e 's/0.0.0/${{ inputs.version }}/g' ./client/setup.cfg

      - name: Package and Upload
        run: ./gen_pypi.sh

