name: Update Pypi
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of python package to deploy"
        required: true
        type: string
jobs:
  python:
    name: Package Python
    environment: Deployment
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: dashboard/package-lock.json

      - name: Install
        run: npm i
        working-directory: ./dashboard

      - name: Install grpc_tools
        run: pip install grpcio-tools==1.62.2

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Install Build Deps
        run: |
          pip install build
          pip install twine

      - name: Set Version Number
        run: sed -i -e 's/0.0.0/${{ inputs.version }}/g' ./client/setup.cfg

      - name: Package and Upload
        run: ./gen_pypi.sh
