name: Integration Testing
on: push

jobs:
  typesense:
    name: Typesense Integration Test
    runs-on: ubuntu-latest
#    container:
#      image: typesense/typesense:0.22.2
#      env:
#        TYPESENSE_API_KEY: xyz
#        TYPESENSE_DATA_DIR: /data
#      ports:
#        - 8108
#      volumes:
#        - /tmp/typesense-data:/data
    steps:

      - name: check os version
        run: cat /etc/os-release
      - name: install container
        run: docker pull typesense/typesense:0.22.2
      - name: Start Typesense
        run: |
          export TYPESENSE_API_KEY=xyz
          mkdir /tmp/typesense-data
          docker run -p 8108:8108 -v/tmp/typesense-data:/data typesense/typesense:0.22.2 \
          --data-dir /data --api-key=$TYPESENSE_API_KEY --enable-cors

      - name: Health Check
        run: curl http://localhost:8108/health

