name: Integration Testing
on: push

jobs:
  typesense:
    runs-on: ubuntu-latest
    container:
      image: typesense/typesense:0.22.2
      env:
        TYPESENSE_API_KEY: xyz
        TYPESENSE_DATA_DIR: /data
      ports:
        - 8108
      volumes:
        - /tmp/typesense-data:/data

