name: Integration Testing
on: push

jobs:
  typesense:
    name: Start Typesense
    runs-on: ubuntu-latest
    steps:

      - name: check os version
        run: cat /etc/os-release
      - name: install container
        run: docker pull typesense/typesense:0.22.2
      - name: Start Typesense
        run: |
          export TYPESENSE_API_KEY=xyz
          mkdir /tmp/typesense-data
          docker run -d -p 8108:8108 -v/tmp/typesense-data:/data typesense/typesense:0.22.2 \
          --data-dir /data --api-key=$TYPESENSE_API_KEY --enable-cors
      - name: Health Check
        run: curl http://localhost:8108/health
      

#  integration_test:
#    needs: typesense
#    name: Test Typesense
#    runs-on: ubuntu-latest
#    steps:
