name: Check All Public Links

on: [push]

jobs:
  github-link-check:
    runs-on: ubuntu-latest
    name: Check github readme repos for broken links
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".readme_mlc_config.json"
          file-path: "./README.md ./CODE_OF_CONDUCT.md CONTRIBUTING.md"
          max-depth: 2
  docs-link-check:
    runs-on: ubuntu-latest
    name: Check docs for broken links
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".docs_mlc_config.json"
          folder-path: "embeddinghub/docs"
          max-depth: 2
  # Commenting out the website link checker until it can be moved to its own workflow
  # website-link-checker:
  #   runs-on: ubuntu-latest
  #   name: broken-link-check
  #   steps:
  #     - name: Check for broken links
  #       id: link-report
  #       uses: celinekurpershoek/link-checker@master
  #       with:
  #         # Required:
  #         url: "https://www.featureform.com/"
  #         # optional:
  #         honorRobotExclusions: false
  #         ignorePatterns: "*linkedin*,*autodesk*,*crunchbase*" # Linkedin returns 999 error to web scrapers
  #         recursiveLinks: true
  #     - name: Print result
  #       run: echo "${{steps.link-report.outputs.result}}"
