name: Check All Public Links

on: push
# on:
#   push:
#     branches:
#       - main
#   schedule:
#     # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
#     - cron: "0 9 * * *"

jobs:
  github-link-check:
    runs-on: ubuntu-latest
    name: Check github readme repos for broken links
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".readme_mlc_config.json"
          file-path: "./README.md ./CODE_OF_CONDUCT.md CONTRIBUTING.md"
          max-depth: 2
  docs-link-check:
    runs-on: ubuntu-latest
    name: Check docs for broken links
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".docs_mlc_config.json"
          folder-path: "docs"
          max-depth: 2
  website-link-checker:
    runs-on: ubuntu-latest
    name: Check featureform website for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.1
        with:
          # Required:
          url: "https://www.featureform.com/"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google,linkedin"
          recursiveLinks: true
      - name: Print result
        run: echo "${{steps.link-report.outputs.result}}"
