name: Slack PR Notify
on: push

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  notify-job:
    name: Notify
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate JSON
        run: echo "DATA=$(./.github/helpers/open_prs.sh)" >> $GITHUB_ENV

      - name: Check JSON
        run: echo $DATA

      - name: Send custom JSON data to Slack workflow
        run: curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} -d "$(./.github/helpers/open_prs.sh)"
#        id: slack
#        uses: slackapi/slack-github-action@v1.24.0
#        with:
#          # This data can be any valid JSON from a previous step in the GitHub Action
#          payload: |
#            $DATA
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}